sudo: required
services:
  - docker
env:
  - DOCKER_IMAGE=pschmitt/picamera
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t "$DOCKER_IMAGE" .
  - docker push "$DOCKER_IMAGE"
